services:
  showtimes:
    build: .
    image: ghcr.io/syntaxxhd/showtimes:latest
    ports:
      - "3000:3000"
    volumes:
      - showtimes-data:/app/data
    environment:
      DB_PATH: /app/data/showtimes.db

volumes:
  showtimes-data:
